### ISSUE TITLE
Issue with Tetris Mini-Game Script for RPG Maker VX Ace

### ISSUE THREAD

**Issue by EggSandvich** [GGZiron/My-Works#1] opened 2019-07-09 18:03 UTC
My bad if this has been reported to you already, but I seem to have encountered an issue with the Tetris Mini-Game script. If you attempt to start a game of Tetris through the script call in a file that has existed before the script was added, the following error is recieved: "Script [Script Name] line 767: NoMethodError occurred. undefined method '+' for nil:NilClass". I tried using the Tetris Mini-Game with the same project, except starting a new game and then using it, and it works fine.

**Comment by GGZiron** [comment] 2019-07-09 21:32
Hello!
Is my bad that I didn't add that to my description ( I ll edit it as soon I am able to), but this script
adds content in the save file, and extract it when you resume the game. The problem is, that your older save file does not have that content it tries to extract, and that's why it gets to your error.

Or instead to fix description, I might as well simply give some initial values on data, that is not found within the save file, and post an update. Thanks for your report :).

**Comment by GGZiron** [comment] 2019-07-09 21:42
I will fix that in my next version, but if you want to fix it before that, you can do it yourself, doing the
following steps.
1. Open the script in your RPG Maker project.
2. Go around line 757, find the method extract_save_data, and delete the entire method.
3. On its place, copy-paste the edited version of that method: 
    def extract_save_data(contents)
      @best_scores         = contents[:ggzt42_best_scores]
      @last_game_scores    = contents[:ggzt42_last_game_scores]
      @total_actions       = contents[:ggzt42_total_actions]
      @total_deleted_lines = contents[:ggzt42_total_deleted_lines]
      @total_frames        = contents[:ggzt42_total_frames]
      @best_scores   ||=0; @last_game_scores    ||=0
      @total_actions ||=0; @total_deleted_lines ||=0
      @total_frames  ||=0
    end

**Comment by GGZiron** [comment] 2019-07-09 23:56
Just released new version, that fixes this issue, and other issues too.

**Comment by GGZiron** [comment] 2019-07-16 06:49
If you want to report something else, please open new issue, or post under my script thread in RPG Maker forums.

Closing.

**Closed by GGZiron** 2019-07-16 06:49 UTC
